# Mysql install and config
- name: Update apt cache
  apt:
    update_cache: yes

- name: Pre-seed MySQL root password
  debconf:
    name: mysql-server-5.7
    question: "mysql-server/root_password"
    value: "{{ mysql_pass }}"
    vtype: password

- name: Pre-seed MySQL root password
  debconf:
    name: mysql-server-5.7
    question: "mysql-server/root_password_again"
    value: "{{ mysql_pass }}"
    vtype: password

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL 5.7
  apt:
    name: mysql-server-5.7
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started

- name: Copy mysqld.conf to /etc/mysql/
  copy:
    src: mysqldconf.txt
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: '0644'

- name: restart the service
  systemd:
         name:  mysql
         state: restarted

# Executing query
- name: Execute MySQL query
  shell: |
        mysql -u root -p'{{ mysql_pass }}' -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '{{ mysql_pass }}' WITH GRANT OPTION; FLUSH PRIVILEGES;"
