- name: making directory
  hosts: build
  become: true
  vars:
    algorithms_pt:
            image_name: algorithms-pt
            image_version: 1.0.1
    
    neptune_api:
            image_name: neptune-api
            image_version: 1.0.1


  roles:
    # - algorithms-build
    - neptune-build

